version: "3.9"
services:
  frontend:
    build:
      context: "./frontend-vue-js"
      dockerfile: "./Dockerfile"
    ports:
      - "5000:5000"
    networks:
      - events_net
  backend:
    build:
      context: "./backend-flask"
      dockerfile: "./Dockerfile"
    ports:
      - "8080:80"
    networks:
      - events_net


networks:
  events_net: