version: "3.9"
services:
  frontend:
   environment:
      BACKEND_URL: "https://5000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build:
      context: "./frontend-vue-js"
      dockerfile: "./Dockerfile"
    ports:
      - "5000:5000"
    networks:
      - events_net
  backend:
      environment:
      FRONTEND_URL: "https://80-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://5000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build:
      context: "./backend-flask"
      dockerfile: "./Dockerfile"
    ports:
      - "8080:80"
    networks:
      - events_net


networks:
  events_net: